name: Build Container Backend image
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: staging

jobs:
  build-image:
    name: Build and push to DockerHub
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    outputs:
        image_tag: ${{ steps.pull_request_id.outputs.image_tag }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.5.0
  
      - name: Checkout
        uses: actions/checkout@v4.1.1
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: kerdockert/app:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to:  type=gha,mode=max
        
      - name: Scan image with Trivy
        id: scan-image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: docker.io/kerdockert/app:${{ inputs.image_tag }}
          format: "sarif"
          severity: "CRITICAL,HIGH"
          vuln-type: 'os,library'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true   