name: Deploy dev enviroment
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - app/**/*.js
      - app/**/package.json
      - app/**/package.lock.json
      - app/**/Dockerfile
      - app/**/helmchart/*
      - app/**/codecov.yml
      - .github/workflows/dev.yml
    types: [opened, synchronize, reopened, labeled]

jobs:
  test:
    name: 'Analyze Code and Testing'
    runs-on: ubuntu-24.04
    outputs:
      image_tag: ${{ steps.pull_request_id.outputs.image_tag }}
    environment: development
    defaults:
      run:
        working-directory: app
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Clean install modules
      run: npm ci
    
    - name: Unit Testing and Code Coverage
      run: |-
        npm run test
        npm run coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Shorten commit SHA
      id: pull_request_id
      run: |
        SHORTEN_SHA=$(echo "${{ github.head_ref }}" | sha256sum | cut -c 1-5)
        echo "image_tag=$SHORTEN_SHA" >> $GITHUB_OUTPUT

  build-image:
    needs: [test]
    uses: ./.github/workflows/build.yml
    with:
      working_directory: app
      environment: development
      image_tag: ${{ needs.test.outputs.image_tag }}
    secrets: inherit

  deploy:
    needs: [build-image, test]
    uses: ./.github/workflows/deploy.yml
    with:
      working_directory: app/helmapp
      environment: development
      image_tag: ${{ needs.test.outputs.image_tag }}
    secrets: inherit
