name: Deploy production enviroment
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    name: 'Analyze Code and Testing'
    runs-on: ubuntu-24.04
    outputs:
      image_tag: ${{ steps.image_info.outputs.image_tag }}
    environment: production
    defaults:
      run:
        working-directory: app
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Clean install modules
      run: npm ci
    
    - name: Unit Testing and Code Coverage
      run: |-
        npm run test
        npm run coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Setting image info
      id: image_info
      run: |
        echo "image_tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

  build-image:
    needs: [test]
    uses: ./.github/workflows/ci-build.yml
    with:
      working_directory: app
      environment: production
      image_tag: ${{ needs.test.outputs.image_tag }}
    secrets: inherit

  deploy:
    needs: [build-image, test]
    uses: ./.github/workflows/cd-deploy.yml
    with:
      working_directory: app/helmapp
      environment: production
      image_tag: ${{ needs.test.outputs.image_tag }}
      stage_name: prod
    secrets: inherit
