name: Deploy staging enviroment
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
      - app/**/*.js
      - app/**/package.json
      - app/**/package.lock.json
      - app/**/Dockerfile
      - app/**/helmchart/*
      - app/**/codecov.yml
      - .github/workflows/dev.yml
      - .github/workflows/cd-deploy.yml
      - .github/workflows/ci-build.yml
      - .github/workflows/cd-clean.yml
      - .github/workflows/staging.yml
    types: [closed]

jobs:
  test:
    name: 'Analyze Code and Testing'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    outputs:
      image_tag: ${{ steps.image_info.outputs.image_tag }}
    environment: staging
    defaults:
      run:
        working-directory: app
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Clean install modules
      run: npm ci
    
    - name: Unit Testing and Code Coverage
      run: |-
        npm run test
        npm run coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Setting image info
      id: image_info
      run: |
        echo "image_tag=latest" >> $GITHUB_OUTPUT

  build-image:
    if: github.event.pull_request.merged == true
    needs: [test]
    uses: ./.github/workflows/ci-build.yml
    with:
      working_directory: app
      environment: staging
      image_tag: ${{ needs.test.outputs.image_tag }}
    secrets: inherit

  deploy:
    if: github.event.pull_request.merged == true
    needs: [build-image, test]
    uses: ./.github/workflows/cd-deploy.yml
    with:
      working_directory: app/helmapp
      environment: staging
      image_tag: ${{ needs.test.outputs.image_tag }}
      stage_name: ${{ needs.test.outputs.image_tag }}
    secrets: inherit
